### ISSUE TITLE
Builds are broken

### ISSUE THREAD

**Issue by probonopd** [linuxdeploy/linuxdeploy-plugin-appimage#1]
Builds are broken with `ERROR: Could not find dependency: libffi.so.5 `.

Note that `squashfs-root/usr/lib/libffi.so.5` is already deployed. https://travis-ci.org/linuxdeploy/linuxdeploy-plugin-appimage/jobs/417058047#L665

**Comment by TheAssassin** [comment]
Travis recently broke some infrastructure. Not sure what's going on, but e.g., appimaged's not building any more, too. Will look into it.

**Comment by TheAssassin** [comment]
`you have held broken packages` -> Travis holds packages -> *scratching head*

**Comment by TheAssassin** [comment]
True, but the question is why the `.6` version is deployed by linuxdeploy (https://travis-ci.org/linuxdeploy/linuxdeploy-plugin-appimage/jobs/417058047#L701).

I guess it is unnecessary to call linuxdeploy on the extracted appimagetool AppDir. I'll remove the call to quick-fix this issue.
