### ISSUE TITLE
Support desktop integration ?

### ISSUE THREAD

**Issue by abcfy2** [linuxdeploy/linuxdeploy-plugin-appimage#11]
I find an AppImage with simple desktop integration implement: https://dl.motrix.app/release/Motrix-1.4.1-x86_64.AppImage

![image](https://user-images.githubusercontent.com/5327677/71228012-eddd1680-231b-11ea-843f-5e58f02a81d4.png)

I think it's cool to support this feature.

**Comment by TheAssassin** [comment]
First of all, integrating any sort of hacky integration stuff has been strongly discouraged for a couple of years now. Second, this is the wrong repository. Please see https://github.com/AppImage/AppImageKit.
