### ISSUE TITLE
It looks like the switch --output has been removed

### ISSUE THREAD

**Issue by Light-Wizzard** [linuxdeploy/linuxdeploy-plugin-appimage#12]
If so, please update the readme.

Thanks.

**Comment by TheAssassin** [comment]
You got this wrong. This is mainly a plugin for linuxdeploy. You can call `linuxdeploy [...] --output appimage` to make linuxdeploy call this plugin.

This plugin is, like all linuxdeploy plugins, controlled through environment variables. There is, and always has been, `$OUTPUT`, which you can set to your desired filename.

**Comment by Light-Wizzard** [comment]
I do not understand, are we talking about this app:

https://github.com/probonopd/linuxdeployqt/blob/master/tools/linuxdeployqt/main.cpp

./linuxdeployqt-continuous-x86_64.AppImage [...] --output appimage

Because it fails in Travis, and I do not see that switch in main.cpp.

Thanks

**Comment by TheAssassin** [comment]
https://docs.appimage.org/packaging-guide/from-source/linuxdeploy-user-guide.html

**Comment by Light-Wizzard** [comment]
Maybe my command line is wrong:

I have tried this on Arch, but it will not work because its too new, but it does give the same error as Ubuntu 16 LTS, and on Travis also.

 ./linuxdeployqt-6-x86_64.AppImage usr/share/applications/GalaxyCalculator.desktop -qmldir=/qml -always-overwrite -appimage --output appimage

linuxdeployqt 5 (commit 37631e5), build 631 built on 2019-01-25 22:47:58 UTC
ERROR: Error: arguments must not start with --, only -: "--output" 

./linuxdeployqt-continuous-x86_64.AppImage usr/share/applications/GalaxyCalculator.desktop -qmldir=/qm" -always-overwrite -appimage --output appimage

linuxdeployqt 6 (commit c6bcad2), build 715 built on 2020-04-12 12:21:56 UTC
ERROR: Error: arguments must not start with --, only -: "--output" 

Can you try this and make sure?

I know that probonopd said that he was removing switches, which is how I stumbled across this information, trying to find out which ones he removed because that one did not work, which you also brought up, but I have never been able to get it to work as the Documents state, so I looked into the Source, and there is no switch called output, I did not look through old releases, I am sure it was there, the documents state so, but I believe they are outdated, and why I submitted this issue, and I do not think it was in error, or because I did not understand the documents, its because it was removed by probonopd, check the source, it does not lie, nor does the error message.

From what he said, the goal is to be compatible with the last LTS and to use the naming convention with the Arch Platform appended to it and setting VERSION to string works, so I gave up after that and will have to live with the ugly name since you cannot rename them after they are made.

I understand his reasons, and I am fine with it, I just did not understand at first.

If my use of it is wrong, that is my bad, but if I am right, and it has been removed, then the documents need to be updated to reflect this decision if it is there, it goes against his principles.

Thanks

**Comment by Light-Wizzard** [comment]
Sorry about this looks like I am getting confused between probonopd and linuxdeploy repos, I did not notice my mistake till now, old age, the first thing to go is the eyes, the second it the mind, or is that already gone...
