### ISSUE TITLE
No AppImage under releases

### ISSUE THREAD

**Issue by qwertysam** [linuxdeploy/linuxdeploy-plugin-appimage#15]
There's no longer a downloadable AppImage, only source code
https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases

**Comment by TheAssassin** [comment]
Sorry for that. I needed to update them, so I deleted the release as usual and tried to restart the build on Travis. However, I have had lots of Internet outages, so I could not trigger a rebuild any more.

I've built a new x86_64 AppImage already, and am looking into the 32-bit build right now.

**Comment by TheAssassin** [comment]
Fixed. Had to find a new strategy, as the CentOS 6 build did not work and after more than an hour, I decided to go for a new strategy. linuxdeploy-plugin-appimage is basically dependency-free, so creating a static build wasn't complicated at all. Now, we have fully static builds which should work on any distro even.
