### ISSUE TITLE
Plugin aborts on irrelevant appstreamcli warning

### ISSUE THREAD

**Issue by kybos** [linuxdeploy/linuxdeploy-plugin-appimage#19]
Hi,

The creation of appimage aborts because of a simple warning in the appdata.xml file:

```
appimagetool, continuous build (commit 0880085), build 2133 built on 2020-07-09 12:25:52 UTC
Using architecture x86_64
/home/kybos/Projects/muse-fork/appimage/appdir should be packaged as MusE-master-x86_64.AppImage
AppStream upstream metadata found in usr/share/metainfo/org.musesequencer.Muse3.appdata.xml
Trying to validate AppStream information with the appstreamcli tool
In case of issues, please refer to https://github.com/ximion/appstream
W - org.musesequencer.Muse3.appdata.xml:org.musesequencer.Muse3:9
    Found empty 'content_rating' tag.

Validation failed: warnings: 1, pedantic: 5
Failed to validate AppStream information with appstreamcli
```
 
Can this be circumvented or changed somehow? I guess this kind of warning shouldn't cause the whole process to abort. 
The problem is that the content_rating tag is required by FlatHub (even empty, as no rating is applicable in our case), so it's quite a deadlock.

Thanks
Kybos

**Comment by TheAssassin** [comment]
I once suggested the AppStream folks to return a different exit code if only warnings are found, but they consider warnings serious issues, too. We don't want to parse the output of this application, we only read the exit code, so we can't differentiate any better. 

Please consider fixing the AppStream file.

**Comment by kybos** [comment]
Thanks for your fast response.
That's exactly what I did, I fixed the AppStream file. With the result that now the flatpack creation fails...
