### ISSUE TITLE
Annyoing [appimage/stdout] and [appimage/stderr] strings in log files

### ISSUE THREAD

**Issue by probonopd** [linuxdeploy/linuxdeploy-plugin-appimage#2]
In log files, the lines are prefixed with annoying and misleading `[appimage/stdout]` and `[appimage/stderr] ` strings which make it hard to read an messy.

https://travis-ci.org/azubieta/appimage-info/builds/420875629#L2904-L2905

```
[appimage/stdout] /home/travis/build/azubieta/appimage-info/AppDir should be packaged as AppImage_Info-x86_64.AppImage
[appimage/stderr] appimagetool, continuous build (commit 56ebd56), build 1818 built on 2018-08-03 15:20:41 UTC
```

**Comment by TheAssassin** [comment]
This is not a mess, but actually _very_ useful. This way, one can clearly see what's going on in plugins, and what output _belongs_ to the plugins. This helps debugging issues on systems like Travis CI.

It's more like a mess that appimagetool doesn't use stderr/stdout correctly.

Nothing to fix here.

**Comment by probonopd** [comment]
"appimage" sounds like some "AppImage" problem when in fact it is the "linuxdeploy AppImage plugin"

**Comment by probonopd** [comment]
Instead of prefixing each(!) line, you could have one line saying `*** linuxdeploy AppImage plugin running now ***` or something like that, so users would know where the following lines belong to

**Comment by TheAssassin** [comment]
That's a feature, and documented behavior. `qt` stands for the `qt` plugin, etc.

I think there is a general issue with "plugin names". For instance, as you noticed `--list-plugins` does show the plugin names, but they might not be taken as such by the user.

**Comment by TheAssassin** [comment]
> Instead of prefixing each(!) line, you could have one line saying *** linuxdeploy AppImage plugin running now *** or something like that, so users would know where the following lines belong to

That used to be the default, however one could never be sure who's created what message (especially when plugins use the logging framework linuxdeploy's libraries provide). Prefixing the output clarifies the situation.

**Comment by probonopd** [comment]
Maybe it's a matter of personal preference, but I think the current solution looks too "technical" and too "complicated". Not eye-friendly to me.
