### ISSUE TITLE
Option to not compress

### ISSUE THREAD

**Issue by andy5995** [linuxdeploy/linuxdeploy-plugin-appimage#23]
Can an option be added to linuxdeploy so the AppImage won't be compressed when it's created?

**Comment by TheAssassin** [comment]
I think what makes more sense is to expose appimagetool's compression setting directly, this way you can configure this completely yourself.

**Comment by andy5995** [comment]
I'm not sure how needed this is actually. Does anyone else think it would be a good option to have?

I'm making app images for 0ad and that project distributes their data in a compressed zip file already, over 1G, and that zip file normally just stays zipped when the game is installed. When making an appimage, the included libraries take up about 180 MB.

I'm just not sure if any performance hits are significant from the appimage decompression at run time, plus 0ad decompressing data at run-time.

But I don't expect anyone here to have intimate knowledge of 0ad implementations, just kind of wondering if anyone else thinks having an option to not-compress an appimage might generally be a useful feature.

**Comment by andy5995** [comment]
> I think what makes more sense is to expose appimagetool's compression setting directly, this way you can configure this completely yourself.

That makes sense to me. (I didn't see your comment until after I finished posting mine)

**Comment by TheAssassin** [comment]
It's totally fine to have that option, it's not a lot of work anyway.

Regarding decompression, one of my projects, [Blue Nebula](https://github.com/blue-nebula/release/releases/tag/continuous), uses the standard compression algorithm (zlib), and the performance is reasonably good.

Overall, what might be suited best for games is Zstandard, since its decompression speed is a fair bit better than zlib, even though compressing takes a lot longer.

**Comment by vladislavbelov** [comment]
> I'm making app images for 0ad and that project distributes their data in a compressed zip file already, over 1G, and that zip file normally just stays zipped when the game is installed.

Currently we don't decompress data for 0 A.D. Its zip files are plane data (kind of tar without compression) to be able to do a fast read.

**Comment by TheAssassin** [comment]
Implemented `$APPIMAGE_COMP`. Note that:

- appimagetool does not support "no compression" at the moment, please open an issue in https://github.com/AppImage/AppImageKit or comment to an existing one to bring it to attention
- linuxdeploy needs to be rebuilt to contain an up-to-date AppImage plugin, so you need to download the AppImage plugin yourself currently to use the latest version
