### ISSUE TITLE
ERROR: Failed to run plugin: appimage

### ISSUE THREAD

**Issue by probonopd** [linuxdeploy/linuxdeploy-plugin-appimage#4]
There are situations when we are trying to sign but there is no key (for example, when we are on git pull requests). In this case, a warning should be printed and the AppImage creation should continue/fall back without signature.

We are getting

> ERROR: gpg2 command did not succeed, could not sign, **continuing**

but it fails nevertheless:

```
[appimage/stderr] gpg2 and sha256sum are installed and user requested to sign, hence signing
[appimage/stderr] /usr/bin/sha256sum appimaged-x86_64.AppImage
[appimage/stderr] /usr/bin/gpg2 --batch --detach-sign --armor   appimaged-x86_64.AppImage.digest
[appimage/stderr] gpg: no default secret key: No secret key
[appimage/stderr] gpg: signing failed: No secret key
[appimage/stderr] ERROR: gpg2 command did not succeed, could not sign, continuing
[appimage/stdout] Desktop file: /tmp/appimaged-build-GixH5p/appdir/appimaged.desktop
[appimage/stdout] /tmp/appimaged-build-GixH5p/appdir should be packaged as appimaged-x86_64.AppImage
[appimage/stdout] Size of the embedded runtime: 187976 bytes
[appimage/stdout] updateinformation type: gh-releases-zsync
[appimage/stdout] ui_offset: 175304
[appimage/stdout] ui_length: 1024
[appimage/stdout] sha256sum: 5f18fbcf147a2ae66c70ae229a7e562035527defde782f11535d2fdad88e82b1
ERROR: Failed to run plugin: appimage 
```

References:
* https://travis-ci.org/AppImage/appimaged/jobs/507381706
* https://github.com/AppImage/appimaged/pull/74

**Comment by TheAssassin** [comment]
That's more of an issue for AppImageKit. I assume it exits with state 1, although it shouldn't. The plugin itself is only a shallow wrapper and just forwards exit codes.

**Comment by TheAssassin** [comment]
Should be resolved already.
