### ISSUE TITLE
CentOS 7 64-bit metadata file issue

### ISSUE THREAD

**Issue by kapitainsky** [linuxdeploy/linuxdeploy-plugin-appimage#8]
It works but only when I remove metadata xml file. Otherwise it fails as below:

```
Found appimagetool: /tmp/.mount_linuxdCqqmwp/usr/bin/appimagetool
Running command: /tmp/.mount_linuxdCqqmwp/usr/bin/appimagetool "AppDir" "-g"


appimagetool, continuous build (commit fef038a), build 2093 built on 2019-07-07 12:07:34 UTC
WARNING: appstreamcli command is missing, please install it if you want to use AppStream metadata
Using architecture x86_64
/dev/shm/rclone-browser-1.6.0-d9e3ebe.AppImage/AppDir should be packaged as Rclone_Browser-1.6.0-d9e3ebe-x86_64.AppImage
Deleting pre-existing .DirIcon
Creating .DirIcon symlink based on information from desktop file
AppStream upstream metadata found in usr/share/metainfo/rclone-browser.appdata.xml
Trying to validate AppStream information with the appstream-util tool
In case of issues, please refer to https://github.com/hughsie/appstream-glib
/dev/shm/rclone-browser-1.6.0-d9e3ebe.AppImage/AppDir/usr/share/metainfo/rclone-browser.appdata.xml: FAILED:
• url-not-found         : <screenshot> failed to connect: SSL handshake failed [https://github.com/kapitainsky/RcloneBrowser/wiki/images/IMGdefault.png]
• url-not-found         : <screenshot> failed to connect: SSL handshake failed [https://github.com/kapitainsky/RcloneBrowser/wiki/images/IMGtransfer.png]
Validation of files failed
Failed to validate AppStream information with appstream-util
rename: Rclone_Browser*: rename to rclone-browser* failed: No such file or directory
cp: cannot stat ‘*AppImage’: No such file or directory

```

the same metadata xml file works perfectly on Ubuntu 16.04.

Both urls it complains about are valid.

**Comment by TheAssassin** [comment]
Like #9 an issue for AppImageKit.

**Comment by TheAssassin** [comment]
Please open an issue upstream at https://github.com/AppImage/AppImageKit.

**Comment by probonopd** [comment]
Actually, as the message says, 

> In case of issues, please refer to https://github.com/hughsie/appstream-glib

**Comment by TheAssassin** [comment]
I think at some point appimagetool should just warn about failed validation but not exit... It's getting increasingly annoying to remain compatible.

**Comment by TheAssassin** [comment]
Anyway, not the plugin's fault. You'll have to adjust your AppStream config. (Or just uninstall `appstreamcli`.)

**Comment by kapitainsky** [comment]
> Anyway, not the plugin's fault. You'll have to adjust your AppStream config. (Or just uninstall `appstreamcli`.)

There is no appstreamcli on centos 7.  I tried to compile it from source but it is not doable.  At least not easy as they moved with dev to tools versions not available on this OS. So appimage is trying to use appstream-util. This is why it works on Ubuntu. And appstream-util is showing very stupid error message that my screenshots urls are not reachable. They are. 

Now what I don’t get why don’t you bundle tool like appstream cli in your tool AppImage? I thought this is the key concept. To avoid missing dependencies.

**Comment by TheAssassin** [comment]
Because appstream-cli yields different results in different versions. It's really, really annoying. Maybe open an issue about including it over at AppImageKit? This plugin just bundles appimagetool internally, it's a shallow wrapper.

**Comment by probonopd** [comment]
Yes @TheAssassin, please see https://github.com/AppImage/AppImageKit/issues/1011#issuecomment-558357215.
